site_name: Moje projekty
site_author: Maciej Sobczak
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

theme:
  name: material
  palette:
    primary: yellow

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "test" : TEST/index.md
- Poprzednie projekty:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md